### ISSUE TITLE
Comparing Allele-specific HiC matrices

### ISSUE THREAD

**Issue by StephenRicher** [dozmorovlab/HiCcompare#25]
Hi,

Thanks for developing this fantastic tool. I was wondering if this tool was recommended for comparing between HiC matrices of different alleles (e.g. A1 vs. A2). 

Thanks,
Stephen

**Comment by mdozmorov** [comment]
We have not tested it, but by design, HiCcompare should be ideal for allele-specific Hi-C matrix comparison. It will eliminate all technical biases and detect if there are interaction differences associated with allele-specific regions.

Hope that helps, closing, but please ask more and let know how it went.
