### ISSUE TITLE
The vignettee's instruction for excluding CNV may need some further calrification

### ISSUE THREAD

**Issue by xs254** [dozmorovlab/HiCcompare#33]
Sorry if I raise a trivial question as I am quite new to the field of HiC. 
I am trying to compare the HiC results from a pair of knockout and control cell line. According to the vignettee, it is recommneded to remove CNV when generating the hic.table object. I think there are two ways to do that:

1) In the first way, I can get CNV from the KO and control group respectively by using CNV detection algorithm that does not require a referenece. And then use the union of KO_CNV and Control_CNV as the regions to exclude: exclude <-cbind(KO_CNV,Control_CNV)
2) In the second way, I can use a CNV detection algorithm that requires reference signal and use control as the reference to find the 'extra' CNV caused by KO and only exlcude the extra CNV.

Given that QDNAseq used by get_CNV does not require a reference signal, I guess approach 1) is preferred? I think it would be better if the vignettee can have more clarification on this process.

**Comment by mdozmorov** [comment]
I would recommend a different approach. Detect differential interactions as you normally would. Detect CNVs using any tool. Check if some boundaries, of whole interactions with both boundaries, overlap them - these are candidates for being differential due to CNVs.

One note is about CNVs - do you expect KO would introduce a lot of them? I would doubt it and won't be concerned. We've been trying various CNV detection methods only to find out many CNVs are false positives, artifacts of either the technology, alignment, or both. It can easily be seen by comparing one normal genome vs. another.

**Comment by xs254** [comment]
Many thanks for the clarification! If I understand correctly, you recommend
detecting CNVs separately *without removing CNVs* from the data for
HiCcompare. The CNV detection results can be used as an extra layer of
information for interpreting the differential interactions detected by
HiCcompare.

Regarding whether KO would introduce a lot of CNVs. To be honest, I also
doubt it, but given that this is a cancer cell line, my original incentive
for CNV removal is to have an extra layer of security. However, as you have
mentioned, CNV detection algorithms are prone to false positives and thus
removing CNV might cause more bad than good.

**Comment by mdozmorov** [comment]
Yes. Even if CNVs are present and result in differential interactions, that's a perfectly valid result. Closing, but please ask more if still in doubt.
